package com.metis.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("t_z_client", "id", ZClient.class);
		arp.addMapping("t_z_client_call", "id", ZClientCall.class);
		arp.addMapping("t_z_client_contact", "id", ZClientContact.class);
		arp.addMapping("t_z_client_opp", "id", ZClientOpp.class);
		arp.addMapping("t_z_client_potential", "id", ZClientPotential.class);
		arp.addMapping("t_z_user", "id", ZUser.class);
	}
}

