package com.metis.common.model;

import com.metis.common.model.base.BaseSession;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Session extends BaseSession<Session> {

    /**
     * 登录会话是否已过期
     */
    public boolean isExpired() {
        return getExpireAt() < System.currentTimeMillis();
    }

    /**
     * 登录会话是否未过期
     */
    public boolean notExpired() {
        return ! isExpired();
    }
	
}
