package com.metis.common.model;

import com.metis.common.model.base.BaseZClientCall;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZClientCall extends BaseZClientCall<ZClientCall> {
	
}
