package com.metis.common.model;

import com.metis.common.model.base.BaseZClientContact;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZClientContact extends BaseZClientContact<ZClientContact> {
	
}
