package com.metis.common.model;

import com.metis.common.model.base.BaseZCompany;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZCompany extends BaseZCompany<ZCompany> {
	
}
