package com.metis.common.model;

import com.metis.common.model.base.BaseZDepartment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZDepartment extends BaseZDepartment<ZDepartment> {
	
}
