package com.metis.common.model;

import com.metis.common.model.base.BaseZLeadInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZLeadInfo extends BaseZLeadInfo<ZLeadInfo> {
	
}
