package com.metis.common.model;

import com.metis.common.model.base.BaseZMClientPartitionScore;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZMClientPartitionScore extends BaseZMClientPartitionScore<ZMClientPartitionScore> {
	
}
