package com.metis.common.model;

import com.metis.common.model.base.BaseZMClientPartition;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZMClientPartition extends BaseZMClientPartition<ZMClientPartition> {
}
