package com.metis.common.model;

import com.metis.common.model.base.BaseZResources;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZResources extends BaseZResources<ZResources> {
	
}
