package com.metis.common.model;

import com.metis.common.model.base.BaseZResource;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZResource extends BaseZResource<ZResource> {
    private List<ZResource> child;

    public List<ZResource> getChild() {
        return child;
    }

    public void setChild(List<ZResource> child) {
        this.child = child;
    }

}
