package com.metis.common.model;

import com.metis.common.model.base.BaseZTSurveyItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZTSurveyItem extends BaseZTSurveyItem<ZTSurveyItem> {
	
}
