package com.metis.common.model;

import com.metis.common.model.base.BaseZTSurvey;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZTSurvey extends BaseZTSurvey<ZTSurvey> {
	
}
