package com.metis.common.model;

import com.metis.common.model.base.BaseZUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZUser extends BaseZUser<ZUser> {

    public ZUser removeSensitiveInfo() {
        remove("password", "salt");
        return this;
    }
}
