package com.metis.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZClientOpp<M extends BaseZClientOpp<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setClientId(java.lang.Integer clientId) {
		set("clientId", clientId);
	}
	
	public java.lang.Integer getClientId() {
		return getInt("clientId");
	}

	public void setBizType(java.lang.String bizType) {
		set("bizType", bizType);
	}
	
	public java.lang.String getBizType() {
		return getStr("bizType");
	}

	public void setProjectName(java.lang.String projectName) {
		set("projectName", projectName);
	}
	
	public java.lang.String getProjectName() {
		return getStr("projectName");
	}

	public void setLocation(java.lang.String location) {
		set("location", location);
	}
	
	public java.lang.String getLocation() {
		return getStr("location");
	}

	public void setClientOwner(java.lang.String clientOwner) {
		set("clientOwner", clientOwner);
	}
	
	public java.lang.String getClientOwner() {
		return getStr("clientOwner");
	}

	public void setOwnerTitle(java.lang.String ownerTitle) {
		set("ownerTitle", ownerTitle);
	}
	
	public java.lang.String getOwnerTitle() {
		return getStr("ownerTitle");
	}

	public void setOwnerEmail(java.lang.String ownerEmail) {
		set("ownerEmail", ownerEmail);
	}
	
	public java.lang.String getOwnerEmail() {
		return getStr("ownerEmail");
	}

	public void setOwnerPhone(java.lang.String ownerPhone) {
		set("ownerPhone", ownerPhone);
	}
	
	public java.lang.String getOwnerPhone() {
		return getStr("ownerPhone");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setUpdateAt(java.lang.String updateAt) {
		set("updateAt", updateAt);
	}
	
	public java.lang.String getUpdateAt() {
		return getStr("updateAt");
	}

	public void setFollowUp(java.lang.String followUp) {
		set("followUp", followUp);
	}
	
	public java.lang.String getFollowUp() {
		return getStr("followUp");
	}

	public void setProposalLead(java.lang.String proposalLead) {
		set("proposalLead", proposalLead);
	}
	
	public java.lang.String getProposalLead() {
		return getStr("proposalLead");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

}
