package com.metis.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZResource<M extends BaseZResource<M>> extends Model<M> implements IBean {

	public void setIncId(java.lang.Integer incId) {
		set("incId", incId);
	}
	
	public java.lang.Integer getIncId() {
		return getInt("incId");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}
	
	public java.lang.String getCode() {
		return getStr("code");
	}

	public void setParent(java.lang.String parent) {
		set("parent", parent);
	}
	
	public java.lang.String getParent() {
		return getStr("parent");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setHref(java.lang.String href) {
		set("href", href);
	}
	
	public java.lang.String getHref() {
		return getStr("href");
	}

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setIcon(java.lang.String icon) {
		set("icon", icon);
	}
	
	public java.lang.String getIcon() {
		return getStr("icon");
	}

	public void setTarget(java.lang.String target) {
		set("target", target);
	}
	
	public java.lang.String getTarget() {
		return getStr("target");
	}

	public void setPermissions(java.lang.String permissions) {
		set("permissions", permissions);
	}
	
	public java.lang.String getPermissions() {
		return getStr("permissions");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

}
