package com.metis.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZMClientPartition<M extends BaseZMClientPartition<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setClientName(java.lang.String clientName) {
		set("clientName", clientName);
	}
	
	public java.lang.String getClientName() {
		return getStr("clientName");
	}

	/**
	 * 造车新势力 是/否
	 */
	public void setNewPlayer(java.lang.String newPlayer) {
		set("newPlayer", newPlayer);
	}
	
	/**
	 * 造车新势力 是/否
	 */
	public java.lang.String getNewPlayer() {
		return getStr("newPlayer");
	}

	/**
	 * 销量 辆
	 */
	public void setSalesVol(java.math.BigDecimal salesVol) {
		set("salesVol", salesVol);
	}
	
	/**
	 * 销量 辆
	 */
	public java.math.BigDecimal getSalesVol() {
		return get("salesVol");
	}

	/**
	 * 平均销售增长率 %
	 */
	public void setIncRate(java.math.BigDecimal incRate) {
		set("incRate", incRate);
	}
	
	/**
	 * 平均销售增长率 %
	 */
	public java.math.BigDecimal getIncRate() {
		return get("incRate");
	}

	/**
	 * 当年开发车型数量 小改款不算
	 */
	public void setNewModelCnt(java.math.BigDecimal newModelCnt) {
		set("newModelCnt", newModelCnt);
	}
	
	/**
	 * 当年开发车型数量 小改款不算
	 */
	public java.math.BigDecimal getNewModelCnt() {
		return get("newModelCnt");
	}

	/**
	 * 品牌档次
	 */
	public void setBrandCat(java.lang.String brandCat) {
		set("brandCat", brandCat);
	}
	
	/**
	 * 品牌档次
	 */
	public java.lang.String getBrandCat() {
		return getStr("brandCat");
	}

	/**
	 * 股东背景/股权结构/融资状况
	 */
	public void setHolderCat(java.lang.String holderCat) {
		set("holderCat", holderCat);
	}
	
	/**
	 * 股东背景/股权结构/融资状况
	 */
	public java.lang.String getHolderCat() {
		return getStr("holderCat");
	}

	/**
	 * 客户信用风险级别 天眼查法律纠纷数量
	 */
	public void setRiskLevel(java.math.BigDecimal riskLevel) {
		set("riskLevel", riskLevel);
	}
	
	/**
	 * 客户信用风险级别 天眼查法律纠纷数量
	 */
	public java.math.BigDecimal getRiskLevel() {
		return get("riskLevel");
	}

	/**
	 * 综合得分
	 */
	public void setScore(java.math.BigDecimal score) {
		set("score", score);
	}
	
	/**
	 * 综合得分
	 */
	public java.math.BigDecimal getScore() {
		return get("score");
	}

	/**
	 * 客户分区
	 */
	public void setPartition(java.lang.String partition) {
		set("partition", partition);
	}
	
	/**
	 * 客户分区
	 */
	public java.lang.String getPartition() {
		return getStr("partition");
	}

	public void setUpdateAt(java.lang.String updateAt) {
		set("updateAt", updateAt);
	}
	
	public java.lang.String getUpdateAt() {
		return getStr("updateAt");
	}

}
