package com.metis.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZMClientPartitionScore<M extends BaseZMClientPartitionScore<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setRefId(java.lang.Integer refId) {
		set("refId", refId);
	}
	
	public java.lang.Integer getRefId() {
		return getInt("refId");
	}

	public void setClientName(java.lang.String clientName) {
		set("clientName", clientName);
	}
	
	public java.lang.String getClientName() {
		return getStr("clientName");
	}

	public void setNewPlayer(java.lang.String newPlayer) {
		set("newPlayer", newPlayer);
	}
	
	public java.lang.String getNewPlayer() {
		return getStr("newPlayer");
	}

	public void setSalesVolRank(java.lang.String salesVolRank) {
		set("salesVolRank", salesVolRank);
	}
	
	public java.lang.String getSalesVolRank() {
		return getStr("salesVolRank");
	}

	public void setSalesVolScore(java.lang.String salesVolScore) {
		set("salesVolScore", salesVolScore);
	}
	
	public java.lang.String getSalesVolScore() {
		return getStr("salesVolScore");
	}

	public void setIncRateRank(java.lang.String incRateRank) {
		set("incRateRank", incRateRank);
	}
	
	public java.lang.String getIncRateRank() {
		return getStr("incRateRank");
	}

	public void setIncRateScore(java.lang.String incRateScore) {
		set("incRateScore", incRateScore);
	}
	
	public java.lang.String getIncRateScore() {
		return getStr("incRateScore");
	}

	public void setHolderCatRank(java.lang.String holderCatRank) {
		set("holderCatRank", holderCatRank);
	}
	
	public java.lang.String getHolderCatRank() {
		return getStr("holderCatRank");
	}

	public void setHolderCatScore(java.lang.String holderCatScore) {
		set("holderCatScore", holderCatScore);
	}
	
	public java.lang.String getHolderCatScore() {
		return getStr("holderCatScore");
	}

	public void setRiskLevelRank(java.lang.String riskLevelRank) {
		set("riskLevelRank", riskLevelRank);
	}
	
	public java.lang.String getRiskLevelRank() {
		return getStr("riskLevelRank");
	}

	public void setRiskLevelScore(java.lang.String riskLevelScore) {
		set("riskLevelScore", riskLevelScore);
	}
	
	public java.lang.String getRiskLevelScore() {
		return getStr("riskLevelScore");
	}

	public void setBrandCatRank(java.lang.String brandCatRank) {
		set("brandCatRank", brandCatRank);
	}
	
	public java.lang.String getBrandCatRank() {
		return getStr("brandCatRank");
	}

	public void setBrandCatScore(java.lang.String brandCatScore) {
		set("brandCatScore", brandCatScore);
	}
	
	public java.lang.String getBrandCatScore() {
		return getStr("brandCatScore");
	}

	public void setNewModelCntRank(java.lang.String newModelCntRank) {
		set("newModelCntRank", newModelCntRank);
	}
	
	public java.lang.String getNewModelCntRank() {
		return getStr("newModelCntRank");
	}

	public void setNewModelCntScore(java.lang.String newModelCntScore) {
		set("newModelCntScore", newModelCntScore);
	}
	
	public java.lang.String getNewModelCntScore() {
		return getStr("newModelCntScore");
	}

	public void setWeightedScore(java.lang.String weightedScore) {
		set("weightedScore", weightedScore);
	}
	
	public java.lang.String getWeightedScore() {
		return getStr("weightedScore");
	}

	public void setWeightedScoreRank(java.lang.String weightedScoreRank) {
		set("weightedScoreRank", weightedScoreRank);
	}
	
	public java.lang.String getWeightedScoreRank() {
		return getStr("weightedScoreRank");
	}

	public void setWeightedScoreScore(java.lang.String weightedScoreScore) {
		set("weightedScoreScore", weightedScoreScore);
	}
	
	public java.lang.String getWeightedScoreScore() {
		return getStr("weightedScoreScore");
	}

	public void setWeightedScoreCate(java.lang.String weightedScoreCate) {
		set("weightedScoreCate", weightedScoreCate);
	}
	
	public java.lang.String getWeightedScoreCate() {
		return getStr("weightedScoreCate");
	}

	public void setWeightedScoreCateAdj(java.lang.String weightedScoreCateAdj) {
		set("weightedScoreCateAdj", weightedScoreCateAdj);
	}
	
	public java.lang.String getWeightedScoreCateAdj() {
		return getStr("weightedScoreCateAdj");
	}

	public void setUpdateAt(java.lang.String updateAt) {
		set("updateAt", updateAt);
	}
	
	public java.lang.String getUpdateAt() {
		return getStr("updateAt");
	}

}
