package com.metis.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZTSurveyMatrix<M extends BaseZTSurveyMatrix<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setNum(java.lang.String num) {
		set("num", num);
	}
	
	public java.lang.String getNum() {
		return getStr("num");
	}

	public void setIndexCode(java.lang.String indexCode) {
		set("indexCode", indexCode);
	}
	
	public java.lang.String getIndexCode() {
		return getStr("indexCode");
	}

	public void setBizDate(java.lang.String bizDate) {
		set("bizDate", bizDate);
	}
	
	public java.lang.String getBizDate() {
		return getStr("bizDate");
	}

	public void setBizUnit(java.lang.String bizUnit) {
		set("bizUnit", bizUnit);
	}
	
	public java.lang.String getBizUnit() {
		return getStr("bizUnit");
	}

	public void setUser(java.lang.String user) {
		set("user", user);
	}
	
	public java.lang.String getUser() {
		return getStr("user");
	}

	public void setBizValue(java.math.BigDecimal bizValue) {
		set("bizValue", bizValue);
	}
	
	public java.math.BigDecimal getBizValue() {
		return get("bizValue");
	}

	public void setComment(java.lang.String comment) {
		set("comment", comment);
	}
	
	public java.lang.String getComment() {
		return getStr("comment");
	}

	public void setUpdateDate(java.lang.String updateDate) {
		set("updateDate", updateDate);
	}
	
	public java.lang.String getUpdateDate() {
		return getStr("updateDate");
	}

}
