package com.metis.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZDepartment<M extends BaseZDepartment<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setDepartmentName(java.lang.String departmentName) {
		set("departmentName", departmentName);
	}
	
	public java.lang.String getDepartmentName() {
		return getStr("departmentName");
	}

	public void setDepartmentCode(java.lang.String departmentCode) {
		set("departmentCode", departmentCode);
	}
	
	public java.lang.String getDepartmentCode() {
		return getStr("departmentCode");
	}

	public void setCompanyId(java.lang.Integer companyId) {
		set("companyId", companyId);
	}
	
	public java.lang.Integer getCompanyId() {
		return getInt("companyId");
	}

	public void setHeadId(java.lang.Integer headId) {
		set("headId", headId);
	}
	
	public java.lang.Integer getHeadId() {
		return getInt("headId");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

}
