package com.metis.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZTSurvey<M extends BaseZTSurvey<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setSurveyNum(java.lang.String surveyNum) {
		set("surveyNum", surveyNum);
	}
	
	public java.lang.String getSurveyNum() {
		return getStr("surveyNum");
	}

	public void setSubmitter(java.lang.String submitter) {
		set("submitter", submitter);
	}
	
	public java.lang.String getSubmitter() {
		return getStr("submitter");
	}

	public void setAnswers(java.lang.String answers) {
		set("answers", answers);
	}
	
	public java.lang.String getAnswers() {
		return getStr("answers");
	}

	public void setByDate(java.lang.String byDate) {
		set("byDate", byDate);
	}
	
	public java.lang.String getByDate() {
		return getStr("byDate");
	}

}
