package com.metis.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZClient<M extends BaseZClient<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setClientName(java.lang.String clientName) {
		set("clientName", clientName);
	}
	
	public java.lang.String getClientName() {
		return getStr("clientName");
	}

	public void setParentCompany(java.lang.String parentCompany) {
		set("parentCompany", parentCompany);
	}
	
	public java.lang.String getParentCompany() {
		return getStr("parentCompany");
	}

	public void setIndustry(java.lang.String industry) {
		set("industry", industry);
	}
	
	public java.lang.String getIndustry() {
		return getStr("industry");
	}

	public void setChannelType(java.lang.String channelType) {
		set("channelType", channelType);
	}
	
	public java.lang.String getChannelType() {
		return getStr("channelType");
	}

	public void setSatisfaction(java.lang.String satisfaction) {
		set("satisfaction", satisfaction);
	}
	
	public java.lang.String getSatisfaction() {
		return getStr("satisfaction");
	}

	public void setOwnerType(java.lang.String ownerType) {
		set("ownerType", ownerType);
	}
	
	public java.lang.String getOwnerType() {
		return getStr("ownerType");
	}

	public void setRepresent(java.lang.String represent) {
		set("represent", represent);
	}
	
	public java.lang.String getRepresent() {
		return getStr("represent");
	}

	public void setClientCode(java.lang.String clientCode) {
		set("clientCode", clientCode);
	}
	
	public java.lang.String getClientCode() {
		return getStr("clientCode");
	}

	public void setTelephone(java.lang.String telephone) {
		set("telephone", telephone);
	}
	
	public java.lang.String getTelephone() {
		return getStr("telephone");
	}

	public void setWebsite(java.lang.String website) {
		set("website", website);
	}
	
	public java.lang.String getWebsite() {
		return getStr("website");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setCreateBy(java.lang.String createBy) {
		set("createBy", createBy);
	}
	
	public java.lang.String getCreateBy() {
		return getStr("createBy");
	}

	public void setCreateAt(java.lang.String createAt) {
		set("createAt", createAt);
	}
	
	public java.lang.String getCreateAt() {
		return getStr("createAt");
	}

	public void setUpdateBy(java.lang.String updateBy) {
		set("updateBy", updateBy);
	}
	
	public java.lang.String getUpdateBy() {
		return getStr("updateBy");
	}

	public void setUpdateAt(java.lang.String updateAt) {
		set("updateAt", updateAt);
	}
	
	public java.lang.String getUpdateAt() {
		return getStr("updateAt");
	}

	public void setAnnualPlan(java.lang.String annualPlan) {
		set("annualPlan", annualPlan);
	}
	
	public java.lang.String getAnnualPlan() {
		return getStr("annualPlan");
	}

	public void setClientType(java.lang.String clientType) {
		set("clientType", clientType);
	}
	
	public java.lang.String getClientType() {
		return getStr("clientType");
	}

	public void setPriority(java.lang.String priority) {
		set("priority", priority);
	}
	
	public java.lang.String getPriority() {
		return getStr("priority");
	}

	public void setWinRate(java.lang.String winRate) {
		set("winRate", winRate);
	}
	
	public java.lang.String getWinRate() {
		return getStr("winRate");
	}

	public void setSignPlan(java.lang.String signPlan) {
		set("signPlan", signPlan);
	}
	
	public java.lang.String getSignPlan() {
		return getStr("signPlan");
	}

	public void setContactPerson(java.lang.String contactPerson) {
		set("contactPerson", contactPerson);
	}
	
	public java.lang.String getContactPerson() {
		return getStr("contactPerson");
	}

	public void setContactPhone(java.lang.String contactPhone) {
		set("contactPhone", contactPhone);
	}
	
	public java.lang.String getContactPhone() {
		return getStr("contactPhone");
	}

	public void setContactEmail(java.lang.String contactEmail) {
		set("contactEmail", contactEmail);
	}
	
	public java.lang.String getContactEmail() {
		return getStr("contactEmail");
	}

}
