package com.metis.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZCompany<M extends BaseZCompany<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setCompanyName(java.lang.String companyName) {
		set("companyName", companyName);
	}
	
	public java.lang.String getCompanyName() {
		return getStr("companyName");
	}

	public void setCompanyCode(java.lang.String companyCode) {
		set("companyCode", companyCode);
	}
	
	public java.lang.String getCompanyCode() {
		return getStr("companyCode");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public void setBizUnit(java.lang.String bizUnit) {
		set("bizUnit", bizUnit);
	}
	
	public java.lang.String getBizUnit() {
		return getStr("bizUnit");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

}
